CREATE TABLE `academicRoadmaps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`notionPageId` varchar(64) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(255) NOT NULL,
	`institution` varchar(255),
	`programType` varchar(120),
	`formatLabel` varchar(120),
	`durationText` varchar(120),
	`workloadText` varchar(120),
	`summary` text NOT NULL,
	`curriculumText` text,
	`audienceText` text,
	`sourceUrl` text NOT NULL,
	`tagsJson` text NOT NULL,
	`status` enum('draft','published') NOT NULL DEFAULT 'published',
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAtUtc` bigint NOT NULL,
	`updatedAtUtc` bigint NOT NULL,
	CONSTRAINT `academicRoadmaps_id` PRIMARY KEY(`id`),
	CONSTRAINT `academicRoadmaps_notionPageId_unique` UNIQUE(`notionPageId`),
	CONSTRAINT `academicRoadmaps_slug_unique` UNIQUE(`slug`)
);
